### PR TITLE
Improve user log reports

### PR DESCRIPTION
**Pull request by mjllewelyn**
I was talking to Connie on Monday, and she mentioned wanting reports for users. We currently allow users to view all of their own logs, with a "jump to date" feature. This just jumps to the page that the date would be on. Admittedly, this is a bit clunky.

Connie wanted employees to be able to filter their logs by date and by project. I think just adding these filters to the "view all logs" page would be fine. I don't think we necessarily need to go making a bunch of reports. Just show them all their logs, with filter options for start date and end date and a multiselect for projects.

Example: I want to know how long I worked and what all I worked on for KETS between Jan. 3 and Jan 8.

### CODE REVIEW

**Comment by dhuey** [comment]
Screen Shot 2020-02-17 at 12 31 41 PM
Can we make the projects input box the same height as the start/end date? I think that should help some of the spacing

**Comment by dhuey** [comment]
I would also maybe add a back (back to dashboard) link above the filters form, just for ease of navigation

**Comment by dhuey** [comment]
I noticed that the labels on the invoice and payroll reports say "Project ids" and "User ids"

Not sure if this is just due to not being branched off of the latest version of development, because when I fetched and pulled, they show up correctly.

I didn't notice where that would have been changed on this PR, but if it did, those should get changed back

**Comment by mjllewelyn** [comment]
@dhuey Those things should be out there. I did think that adding a back link on the page looks a little weird since the dashboard link in the header is right above it.

Screen Shot 2020-02-18 at 2 44 27 PM

**Comment by dhuey** [comment]
Those look good! I agree, it's weird to have the word "Dashboard" there twice right next to each other. We probably don't need it. I'd just get rid of it

**Pull request merged**
